### ISSUE TITLE
google playstore : baztille unavailable in your country (thailand)

### ISSUE THREAD

**Issue by dachary** [Baztille/app#2]
I tried to install the app from google playstore but the page states "baztille is unavailable in your country". The page otherwise accurately describes baztille and shows the user comments. This is using a SIM card bought in thailand. I will unfortunately be unable to test this further because I'm going back to France in a few hours.

**Comment by dachary** [comment]
the google playstore country list should be adjusted to allow distribution in all countries

![country-list](https://cloud.githubusercontent.com/assets/433594/14941505/df487bd0-0f9e-11e6-84b5-87a7db6090ba.png)

**Comment by citymont** [comment]
it's done. wait for one or two hour before update.

**Comment by dachary** [comment]
@citymont cool, thanks :-) I'm not sure how to test that: I'm no longer in thailand.
